/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    }

    /*maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }*/
}

dependencies {
    compileOnly(libs.org.spigotmc.spigot.api)
}

group = "odyssey"
version = "1.0-SNAPSHOT"
description = "Odyssey"
java.sourceCompatibility = JavaVersion.VERSION_1_8

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
