[versions]
spigot-api = "1.21.8-R0.1-SNAPSHOT"
unimi-fastutil = "8.5.16"

[libraries]
spigot-api = { module = "org.spigotmc:spigot-api", version.ref = "spigot-api" }
unimi-fastutil = { module = "it.unimi.dsi:fastutil", version.ref = "unimi-fastutil"}